webtalk_init -webtalk_dir /home/sarham/rv32i-pipeline-processor/rv32i-pipeline-processor/rv32i-vivado/rv32i-vivado.sim/sim_1/behav/xsim/xsim.dir/microprocessor_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 19 17:08:48 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2af94ee89c5e5d4f937a49c9ddbbd7a8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e2836db11f674e4a9b4023c42b372253" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1817.081 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "168.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "360 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "118628_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1441536708 -regid "" -xml /home/sarham/rv32i-pipeline-processor/rv32i-pipeline-processor/rv32i-vivado/rv32i-vivado.sim/sim_1/behav/xsim/xsim.dir/microprocessor_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/sarham/rv32i-pipeline-processor/rv32i-pipeline-processor/rv32i-vivado/rv32i-vivado.sim/sim_1/behav/xsim/xsim.dir/microprocessor_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/sarham/rv32i-pipeline-processor/rv32i-pipeline-processor/rv32i-vivado/rv32i-vivado.sim/sim_1/behav/xsim/xsim.dir/microprocessor_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
