#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Feb 19 16:53:37 PKT 2025
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim microprocessor_tb_behav -key {Behavioral:sim_1:Functional:microprocessor_tb} -tclbatch microprocessor_tb.tcl -view /home/sarham/rv32i-pipeline-processor/rv32i-pipeline-processor/rv32i-vivado/microprocessor_tb_behav.wcfg -log simulate.log
